(function($){
  let LOCATIONS = (window.PTSEO_LOCAL && PTSEO_LOCAL.preset) || [];
  let DATA = null;
  function fetchData(){ return $.get(ajaxurl,{action:'ptseo_local_get',nonce:(PTSEO_LOCAL?PTSEO_LOCAL.nonce:'')}); }
  function opts($el, arr){ $el.empty(); $el.append('<option></option>'); (arr||[]).forEach(function(o){ $el.append('<option value="'+o.value+'" data-name="'+o.label+'">'+o.label+'</option>'); }); $el.trigger('change.select2'); }
  function listDistricts(){ return Object.keys(DATA.districts).sort().map(function(n){return {value:DATA.districts[n].code,label:n};}); }
  function listMunicipalities(dName){ const m=DATA.districts[dName].municipalities; return Object.keys(m).sort().map(function(n){return {value:m[n].code,label:n};}); }
  function listParishes(dName,mName){ const p=DATA.districts[dName].municipalities[mName].parishes; return Object.keys(p).sort().map(function(c){return {value:c,label:p[c]};}); }
  function renderTags(){ const $l=$('#seoptl_locations_list'); $l.empty(); LOCATIONS.forEach(function(lc,i){ const label=[lc.district_name,lc.municipality_name,lc.parish_name].filter(Boolean).join(', '); const $t=$('<span class="tag">'+label+' <a href="#" data-i="'+i+'">×</a></span>'); $t.find('a').on('click',function(e){e.preventDefault(); LOCATIONS.splice(i,1); renderTags(); saveHidden(); updatePreview();}); $l.append($t); }); saveHidden(); }
  function saveHidden(){ $('#seoptl_locations_input').val(JSON.stringify(LOCATIONS)); }
  function updatePreview(){ const graph = LOCATIONS.map(function(l){ const e={"@type":"LocalBusiness","name":document.title,"url":window.location.origin+"/","image":"","telephone":"","address":{"@type":"PostalAddress","addressCountry":"Portugal"},"areaServed":[]}; if(l.parish_name){ e.address.addressLocality = l.parish_name; e.areaServed.push(l.parish_name); } if(l.municipality_name){ e.address.addressRegion = l.municipality_name; e.areaServed.push(l.municipality_name); } if(l.district_name){ e.areaServed.push(l.district_name); } return e; }); const json = {"@context":"https://schema.org","@graph":graph}; $('#seoptl_preview').text(JSON.stringify(json,null,2)); const last = LOCATIONS[LOCATIONS.length-1] || {}; $('#prev_locality').text(last.parish_name||''); $('#prev_region').text(last.municipality_name||''); $('#prev_area').text([last.parish_name,last.municipality_name,last.district_name].filter(Boolean).join(', ')); }
  $(function(){ const $d=$('#seoptl_district'), $m=$('#seoptl_municipality'), $p=$('#seoptl_parish'); $('.seoptl-select').select2({width:'100%', allowClear:true}); fetchData().done(function(data){ DATA=data||{districts:{}}; if(!DATA.districts || !Object.keys(DATA.districts).length){ $('.seoptl-content').prepend('<div class="notice notice-warning"><p>Para carregar Portugal completo, use <strong>Local — Ferramentas</strong> e clique em <em>Gerar Portugal completo</em>.</p></div>'); } opts($d, listDistricts()); updatePreview(); }); $d.on('change', function(){ const dName=$d.find(':selected').data('name'); if(!dName){ opts($m,[]); opts($p,[]); return; } opts($m, listMunicipalities(dName)); opts($p,[]); }); $m.on('change', function(){ const dName=$d.find(':selected').data('name'); const mName=$m.find(':selected').data('name'); if(!mName){ opts($p,[]); return; } opts($p, listParishes(dName,mName)); }); $('#seoptl_add_location').on('click', function(){ const dName=$d.find(':selected').data('name')||''; const dCode=$d.val()||''; const mName=$m.find(':selected').data('name')||''; const mCode=$m.val()||''; const pName=$p.find(':selected').data('name')||''; const pCode=$p.val()||''; if(!dCode||!mCode||!pCode){ alert('Selecione distrito/ilha, concelho e freguesia.'); return; } LOCATIONS.push({district_code:dCode,district_name:dName,municipality_code:mCode,municipality_name:mName,parish_code:pCode,parish_name:pName}); renderTags(); updatePreview(); }); renderTags(); updatePreview(); });
})(jQuery);
